nl/publications
StuyPulse/team694.github.io pull request #202
Opened 2020-11-06 00:52 UTC by nlin21

Split out publications from resources/documents & tutorials/ into a new directory
Add newsletter redirect to blog and front page

2020-11-06 22:53 UTC, yuna9 requested changes
I left some comments. Also when making changes like these, it's often helpful to include screenshots of the changes. For example, you can show what the new publications page looks like and you can also show the old resources page with the publications gone.

2020-11-06 22:53 UTC, yuna9 commented on blog/index.html
> +        {% if post.title contains "Newsletter" %}
I recommend you instead check for the presence of a `link` variable in the post front matter. It doesn't have to be just newsletters

2020-11-06 22:53 UTC, yuna9 commented on calendar/index.html
> +<iframe src="https://calendar.google.com/calendar/b/2/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=aW5mb0BzdHV5cHVsc2UuY29t&amp;src=c3R1eXB1bHNlLmNvbV9vcWdxZXY
Hm why did this change?

2020-11-06 23:57 UTC, nlin21 commented on calendar/index.html
> +<iframe src="https://calendar.google.com/calendar/b/2/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FNew_York&amp;src=aW5mb0BzdHV5cHVsc2UuY29t&amp;src=c3R1eXB1bHNlLmNvbV9vcWdxZXY
![image](https://user-images.githubusercontent.com/44385887/98425020-b4131c80-2061-11eb-8db8-ff16170cba0e.png)

Without the semi-colon it was returning the error in the picture, but I just tried it without the semi-colon and it still works
I'll just remove the semi-colon to revert the change

2020-11-07 00:41 UTC, yuna9 approved these changes

2020-11-07 00:55 UTC, merged